'use client'

import { Navbar, Sidebar } from '@/components'
import './globals.css'
import { useRouter } from 'next/navigation'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zecht Portofolio",
  description: "Generated by Zecht",
};

export default function RootLayout({ children}: Readonly<{ children: React.ReactNode; }>) {
  const router = useRouter();
  return (
    <html lang="en">
      <head>
        <title>Zecht Porto</title>
      </head>
      <body className={`page  ${sora.variable} font-sora relative `}>
        <Navbar/>
        <Sidebar/>
        {children}
      </body>
    </html>
  )
}